In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [4]:
%timeit [j**4 for j in range(1,9)]

2.28 µs ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
%timeit np.arange(1,9)**4

2.82 µs ± 73.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
x = [1,2,3,4]

y = np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
l = []

for i in range(1,5):
    int_1 = input("enter: ")
    l.append(int_1)

print(np.array(l))

['2' '2' '3' '4']


In [8]:
#1D array - [1 2 3 4]
#2D array - [[1 2 3 4]]
#3D array - [[[1 2 3 4]]]

#to check dimension of array use ndim

In [9]:
x = np.array([1,2,3,4])
print(x)
print(x.ndim)

[1 2 3 4]
1


In [10]:
ar2 = np.array([[1,2,3,4],[5,6,7]])
print(ar2)
print(ar2.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
1


C:\Users\Shashank\AppData\Local\Temp\ipykernel_23736\364399195.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4],[5,6,7]])


In [11]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [13]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [14]:
# special types of arrays 

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
ar_em = np.empty(4)
print(ar_em)
#previous memory data is inserted in to this empty array 

[1. 1. 1. 1.]


In [17]:
#range array 
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [18]:
#diagonal array
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [20]:
#linspace
ar_lin = np.linspace(0,20,num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [21]:
#rand() - random values between 0-1rand
var = np.random.rand(4)
print(var)

[0.13569043 0.80430906 0.64215895 0.14313503]


In [22]:
var = np.random.rand(3,4)
print(var)

[[0.36493702 0.40926547 0.40329777 0.87225525]
 [0.10527366 0.11509264 0.78910393 0.29999587]
 [0.16893471 0.22666036 0.3789951  0.09175014]]


In [23]:
#randn() - random values close to 0.
var = np.random.randn(4);
print(var)

[-1.95553477 -0.26709189  1.63720525 -0.63848474]


In [24]:
var = np.random.randn(2,4);
print(var)

[[ 1.36889291  0.80006468 -1.17420448  0.83140252]
 [ 0.6511906   1.02890701  0.10338568 -1.35637547]]


In [25]:
#ranf 
var = np.random.ranf(4);
print(var)

[0.38565587 0.41744438 0.70903334 0.16314051]


In [26]:
var = np.random.ranf((3,4));
print(var)

[[0.37511667 0.22541298 0.21060789 0.53058016]
 [0.88307881 0.45490103 0.3064338  0.55023454]
 [0.69145284 0.67182212 0.6595855  0.08598994]]


In [27]:
#randint random nos between a range
var = np.random.randint(1,4,10) #(min,max,total value)
print(var)

[2 1 1 1 2 2 3 3 3 3]


In [28]:
#Data types

var = np.array([1,2,3,4])
print(var)
print(var.dtype)

[1 2 3 4]
int32


In [29]:
var = np.array([1.0,2.0,3.0,4.0])
print(var)
print(var.dtype)

[1. 2. 3. 4.]
float64


In [30]:
var = np.array(['s','a'])
print(var)
print(var.dtype)

['s' 'a']
<U1


In [31]:
#converting datatypes 
x = np.array([1,2,3,4])
print(x)
print(x.dtype)

[1 2 3 4]
int32


In [32]:
x = np.array([1,2,3,4],dtype = np.int8)
print(x)
print(x.dtype)

[1 2 3 4]
int8


In [33]:
x = np.array([1,2,3,4],dtype = np.float64)
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float64


In [34]:
x = np.array([1,2,3,4],dtype = "f") #or use float32
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [35]:
x = np.array([1,2,3,4])
new = np.float32(x)
new1 = np.int_(new)


print(new1.dtype)
print(x.dtype)
print(new.dtype)

print(x)
print(new1)
print(new)

int32
int32
float32
[1 2 3 4]
[1 2 3 4]
[1. 2. 3. 4.]


In [36]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [37]:
#shape 

#2D array
var = np.array([[1,2,5],[3,4,5]])
print(var)
print()
print(var.shape)

[[1 2 5]
 [3 4 5]]

(2, 3)


In [38]:
#multi dimension array
var1 = np.array([1,2,3,4], ndmin =5)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


In [39]:
var1 = np.array([[1,2],[3,4]], ndmin =5)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[[1 2]
    [3 4]]]]]
5
(1, 1, 1, 2, 2)


In [40]:
#reshaping np array
var1 = np.array([1,2,3,4,5,6])
print(var1)
print(var1.ndim)

print()

var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(3,2)
print(x)
print(x.ndim)

print()

var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = var3.reshape(2,3,2)
print(y)
print(y.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [41]:
#flattening an array i.e converting it to 1D array


var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = var3.reshape(2,3,2)
print(y)
print(y.ndim)

print()

x1 = y.reshape(-1)
print(x1)
print(x1.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [42]:
#Arthimatic operations 

var = np.array([1,2,3,4])

varadd = var+3
print(varadd)

[4 5 6 7]


In [43]:
var = np.array([1,2,3,4])

varadd = np.add(var,3)
print(varadd)

[4 5 6 7]


In [44]:
var1 = np.array([1,2,3,4])
var2 = np.array([3,3,3,3])

varadd = var1+var2
print(varadd)

#same for /,%,*,- 

[4 5 6 7]


In [45]:
var1 = np.array([1,2,3,4])
var2 = np.array([3,3,3,3])

varadd = np.add(var1,var2) #
print(varadd)

[4 5 6 7]


In [46]:
# a+b np.add(a,b)
# a-b np.subtract(a,b)
# a*b np.multiply(a,b)
# a/b np.divde(a,b)
# a%b np.mod(a,b)
# a**b np.power(a,b)
# 1/a np.reciprocal(a)

In [47]:
#2D array

var11 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[3,3,3,3],[4,4,4,4]])

print(var11)

print()

print(var22)

print()


print(np.add(var11,var22))

[[1 2 3 4]
 [1 2 3 4]]

[[3 3 3 3]
 [4 4 4 4]]

[[4 5 6 7]
 [5 6 7 8]]


In [48]:
var0 = np.array([2,3,1,4,5,2,8,7])

print("min:",np.min(var0), np.argmin(var))
print("max:", np.max(var0), np.argmax(var0))
print("sqrt:", np.sqrt(var0))
print(np.sin(var0))
print(np.cos(var0))
print(np.square(var0))


min: 1 0
max: 8 6
sqrt: [1.41421356 1.73205081 1.         2.         2.23606798 1.41421356
 2.82842712 2.64575131]
[ 0.90929743  0.14112001  0.84147098 -0.7568025  -0.95892427  0.90929743
  0.98935825  0.6569866 ]
[-0.41614684 -0.9899925   0.54030231 -0.65364362  0.28366219 -0.41614684
 -0.14550003  0.75390225]
[ 4  9  1 16 25  4 64 49]


In [49]:
#broadcasting 

# var1 = np.array([1,2,3,4])
# var2 = np.array([1,2,3])

# print(np.add(var1,var2))
#ValueError: operands could not be broadcast together with shapes (4,) (3,)


In [50]:
var1 = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])

print(var1)
print(var1.shape)

print()

print(var2)
print(var2.shape)

print()
print(np.add(var1,var2))

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [51]:
var1 = np.array([1,2,3,4])
var2 = np.array([[1],[2],[3]])

print(np.add(var1,var2))

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [52]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


In [53]:
#Indexing

var = np.array([9,8,7,6])

print(var[1])
print(var[-2])

8
7


In [54]:
var1 = np.array([[9,8,7],[6,5,4]])
print(var1)

print()

print(var1.shape)

print()

print(var1[0][1]) # or print(var1[0,1])


[[9 8 7]
 [6 5 4]]

(2, 3)

8


In [55]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print()
print(var2.ndim)
print()
print(var2[0][1])
print(var2[0][1][1])

[[[1 2]
  [6 7]]]

3

[6 7]
7


In [56]:
var2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var2)
print()
print(var2.ndim)
print(var2[1][0][0])
print(var2[1][0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

3
5
[5 6]


In [57]:
#Slicing  if[1,2,3,4,5,6] to take data from 3-5 i.e [3,4,5]

#1D - start:stop:step
var = np.array([1,2,3,4,5,6,7])
print(var)

print()

print(var[1:5])
print(var[1:5:2])
print(var[:])
print(var[:-1])
print(var[:-1:2])



[1 2 3 4 5 6 7]

[2 3 4 5]
[2 4]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[1 3 5]


In [58]:
#2D array
var1 = np.array([[9,8,7],[6,5,4]])
print(var1[0][0:3])
print(var1[0][0:3:2])
print(var1[1][0:3])
print(var1[1][0:3:2])

[9 8 7]
[9 7]
[6 5 4]
[6 4]


In [59]:
#3D
var2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(var2[0][0][0:6])
print(var2[0][0][0:6:2])
# print(var2[1][0][0:6])
# print(var2[1][0][0:6:2]) not present -> will not execute

[1 2 3 4 5]
[1 3 5]


In [60]:
var2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(var2[0][1][0:5])
print(var2[0][1][0:5:2])
print(var2[1][0][0:5])
print(var2[1][1][0:5:2])

[5 6 7 8]
[5 7]
[ 9 10 11 12]
[13 15]


In [61]:
#Iterating Numpy Arrays


#1D array
x = np.array([1,3,2,5,4,7,6,9,8,10])
print(x)
print()
for i in x:
    print(i)

print()

for i in np.nditer(x):
    print(i)


[ 1  3  2  5  4  7  6  9  8 10]

1
3
2
5
4
7
6
9
8
10

1
3
2
5
4
7
6
9
8
10


In [62]:
#2D array
a = np.array([[1,2,3,4],[1,2,3,4]])
print(a)
print(a.ndim)

print()

for j in a:
    print(j)


print()

for k in a: #selecting the row
    for l in k: #now iterating through that row
        print(l)

print()

for i in np.nditer(a):
    print(i)
        

[[1 2 3 4]
 [1 2 3 4]]
2

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4

1
2
3
4
1
2
3
4


In [63]:
#3D array
b = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[4,5,6,7]]])
print(b)
print(b.ndim)

print()

for i in b:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [4 5 6 7]]]
3

1
2
3
4
1
2
3
4
1
2
3
4
4
5
6
7


In [64]:
b = np.array([[[1,2,3,4],[1,2,3,4]]])
print(b)
print(b.ndim)

print()

for i in np.nditer(b):
    print(i)

print()

for i,d in np.ndenumerate(b): #printing index and data  
    print(i,d)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [65]:
#copy vs views

var = np.array([1,2,3,4])
co = var.copy() #the copy of an array is a new array, if original data is changed (var), it will not affect the data copied in the new array

var[1]=10

print(var)
print(co)

[ 1 10  3  4]
[1 2 3 4]


In [66]:
var = np.array([1,2,3,4])

vi = var.view() #a view of the original array, if original data is changed (var), it will affect the data copied in the new array

var[1]=10

print(var)
print(vi)

[ 1 10  3  4]
[ 1 10  3  4]


In [67]:
# join array 

a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

ar = np.concatenate((a,b))
print(ar)

[1 2 3 4 6 7 8 9]


In [68]:
a1 = np.array([[1,2],[5,6]])
b1 = np.array([[2,2],[3,3]])

ar = np.concatenate((a1,b1),axis = 0)
ar1 = np.concatenate((a1,b1),axis = 1)

print(a1)
print()
print(b1)
print()
print(ar)
print()
print(ar1)

[[1 2]
 [5 6]]

[[2 2]
 [3 3]]

[[1 2]
 [5 6]
 [2 2]
 [3 3]]

[[1 2 2 2]
 [5 6 3 3]]


In [69]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

ar_new = np.stack((a,b),axis=1) #rows
print(ar_new)
print()
ar_new1 = np.stack((a,b),axis=0) #column
print(ar_new1)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]

[[1 2 3 4]
 [6 7 8 9]]


In [70]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

ar_new = np.hstack((a,b)) #rows
print(ar_new)
print()
ar_new1 = np.dstack((a,b)) #column
print(ar_new1)
print()
ar_new1 = np.vstack((a,b)) #column
print(ar_new1)

[1 2 3 4 6 7 8 9]

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]

[[1 2 3 4]
 [6 7 8 9]]


In [71]:
#split array 
var = np.array([1,2,3,4,5,6,7,8])
print(var)

print()

ar = np.array_split(var,3)
print(ar)
print(type(ar))
print()

a = ar[1]
print(a)

[1 2 3 4 5 6 7 8]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
<class 'list'>

[4 5 6]


In [72]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
print()

ar1 = np.array_split(var1,2)
print(ar1)
ar2 = np.array_split(var1,3)
print(ar2)
print()
ar3 = np.array_split(var1,3,axis = 1)
print(ar3)


[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


In [73]:
#search 
var = np.array([4,1,2,3,4,2,5,6,7,])
x = np.where(var == 2)
print(x)

(array([2, 5], dtype=int64),)


In [74]:
var = np.array([1,2,3,4,2,5,6,7,])
x = np.where((var%2) == 0)
print(x)

(array([1, 3, 4, 6], dtype=int64),)


In [75]:
var = np.array([1,2,3,4,6,7,8])

x = np.searchsorted(var,5) # 5 can be inserted in the array at index 4
print(x)
print(var) #won't be shown here

4
[1 2 3 4 6 7 8]


In [76]:
var = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(var,5,side = "right")
print(x)

4


In [77]:
var = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(var,[5,6,7],side = "right")
print(x)

[4 5 6]


In [78]:
#sort
var = np.array([1,3,2,5,4,7,6,9,8])

print(np.sort(var))

[1 2 3 4 5 6 7 8 9]


In [79]:
var = np.array(['a','c','b','e'])
print(np.sort(var))

['a' 'b' 'c' 'e']


In [80]:
var = np.array([[1,4,3],[2,6,5]])
print(np.sort(var))

[[1 3 4]
 [2 5 6]]


In [81]:
#filter array 

var = np.array([1,2,3,4])

f = [True,False,True,False]

new_arr = var[f]
print(new_arr)
print(type(new_arr))


[1 3]
<class 'numpy.ndarray'>


In [82]:
#Shuffle 
var = np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(var)
print(var)

[2 8 5 9 6 4 1 7 3]


In [84]:
#unique
var = np.array([1,2,3,4,2,5,6,2,7])
x = np.unique(var,return_index=True,return_counts=True)
print(x)

[[1 2 3]
 [4 5 6]]


In [83]:
#resize
var = np.array([1, 2, 3, 4, 5, 6])
a = np.resize(var, (2, 3))
print(a)


[[1 2 3]
 [4 5 6]]


In [85]:
#flatten
var = np.array([1, 2, 3, 4, 5, 6])
a = np.resize(var, (2, 3))
print(a.flatten(order='C'))
print()
print(a.flatten(order='F'))

[1 2 3 4 5 6]

[1 4 2 5 3 6]


In [87]:
#ravel
var = np.array([1, 2, 3, 4, 5, 6])
a = np.resize(var, (2, 3))
print(np.ravel(a))
print()
print(np.ravel(a,order="A"))

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [92]:
#insert
var = np.array([1,2,3,4])
print(var)

a = np.insert(var,2,10) #array name, postion, value
print(a)
print()

b = np.insert(var,(2,4),10)
print(b)

[1 2 3 4]
[ 1  2 10  3  4]

[ 1  2 10  3  4 10]


In [97]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
print()

a = np.insert(var,2,6,axis=0)
print(a)

print()

b = np.insert(var,2,6,axis=1)
print(b)

print()

c = np.insert(var,[1,2],6,axis=1)
print(c)

print()

d = np.insert(var,[1,2],6,axis=0)
print(d)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]

[[1 6 2 6 3]
 [1 6 2 6 3]]

[[1 2 3]
 [6 6 6]
 [1 2 3]
 [6 6 6]]


In [98]:
#delete
var = np.array([1,2,3,4])
print(var)

d = np.delete(var, 2)
print(d)

[1 2 3 4]
[1 2 4]


In [102]:
#matrix
var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))

var = np.array([[1,2,3],[1,2,3]])

print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>
[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [120]:
var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2]])

print(var+var1)
print(var-var1)
print(var/var1)
print(var%var1)
#print(var*var1) wont work
print(var.dot(var1))

[[2 4]
 [2 4]]
[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
[[0 0]
 [0 0]]
[[3 6]
 [3 6]]


In [114]:
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [111]:
#transpose
var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.array([[1,2,3],[1,2,3]])
print(var.dot(var1.T)) # need same size matrix or do transpose

[[14 14]
 [14 14]]


In [118]:
# det & inverse
var1 = np.array([[1,2],[1,2]])
print(var1)
print()

print(np.linalg.det(var1))
#print(np.linalg.inv(var1))
#The error you're encountering, LinAlgError: Singular matrix, indicates that the matrix you're attempting to invert is singular. A singular matrix is one that does not have an inverse. This typically occurs when the determinant of the matrix is zero, indicating that the matrix does not have full rank and that its rows or columns are linearly dependent.

[[1 2]
 [1 2]]

0.0


In [119]:
var1 = np.array([[1,2],[3,4]])
print(var1)
print()

print(np.linalg.inv(var1))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [129]:
#matrix power 
var = np.matrix([[1,2],[3,4]])

print(var.dot(var)) #power 2 
print()
print(np.linalg.matrix_power(var,2)) #(var,n) n = 0 -> identity matrix, n>0 -> power is applied i.e dot product, n<0 -> inverse x power.
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [133]:
z = np.matrix([[1,2,3],[2,2,2],[3,3,3]])
print(np.linalg.det(z))

0.0
